LIB_ALGORITHMS_HOME := src/algorithms
VPATH += $(LIB_ALGORITHMS_HOME)

LIB_ALGORITHMS_SRC  := $(notdir $(wildcard $(LIB_ALGORITHMS_HOME)/*.c))
SRC           += $(wildcard $(LIB_ALGORITHMS_HOME)/*.c)

LIB_ALGORITHMS_OBJ_DEBUG    := $(addprefix $(DEBUG_OBJDIR)/,$(LIB_ALGORITHMS_SRC:.c=.o))
LIB_ALGORITHMS_OBJ_RELEASE  := $(addprefix $(RELEASE_OBJDIR)/,$(LIB_ALGORITHMS_SRC:.c=.o))
LIB_ALGORITHMS_OBJ_COVERAGE := $(addprefix $(COVERAGE_OBJDIR)/,$(LIB_ALGORITHMS_SRC:.c=.o))
OBJ += $(LIB_ALGORITHMS_OBJ_DEBUG) $(LIB_ALGORITHMS_OBJ_RELEASE) $(LIB_ALGORITHMS_OBJ_COVERAGE)

LIB_ALGORITHMS_RELEASE  := $(RELEASE_LIBDIR)/libalgorithms.a
LIB_ALGORITHMS_DEBUG    := $(DEBUG_LIBDIR)/libalgorithms.a
LIB_ALGORITHMS_COVERAGE := $(COVERAGE_LIBDIR)/libalgorithms.a

LIB_ALGORITHMS_RELEASE_SO  := $(RELEASE_LIBDIR)/libalgorithms.$(SO_SUFFIX)
LIB_ALGORITHMS_DEBUG_SO    := $(DEBUG_LIBDIR)/libalgorithms.$(SO_SUFFIX)
LIB_ALGORITHMS_COVERAGE_SO := $(COVERAGE_LIBDIR)/libalgorithms.$(SO_SUFFIX)

RELEASE_LIBS    += $(LIB_ALGORITHMS_RELEASE) $(LIB_ALGORITHMS_RELEASE_SO)
DEBUG_LIBS      += $(LIB_ALGORITHMS_DEBUG) $(LIB_ALGORITHMS_DEBUG_SO)
COVERAGE_LIBS   += $(LIB_ALGORITHMS_COVERAGE) $(LIB_ALGORITHMS_COVERAGE_SO)

###############################################################################
release: $(LIB_ALGORITHMS_RELEASE) $(LIB_ALGORITHMS_RELEASE_SO)
debug: $(LIB_ALGORITHMS_DEBUG)  $(LIB_ALGORITHMS_DEBUG_SO)
coverage: $(LIB_ALGORITHMS_COVERAGE) $(LIB_ALGORITHMS_COVERAGE_SO)

$(LIB_ALGORITHMS_RELEASE): $(LIB_ALGORITHMS_OBJ_RELEASE)
	echo "Making libalgorithms release"
	$(AR) ru $@ $(LIB_ALGORITHMS_OBJ_RELEASE)
	$(RANLIB) $@

$(LIB_ALGORITHMS_DEBUG): $(LIB_ALGORITHMS_OBJ_DEBUG)
	echo "Making libalgorithms debug"
	$(AR) ru $@ $(LIB_ALGORITHMS_OBJ_DEBUG)
	$(RANLIB) $@

$(LIB_ALGORITHMS_COVERAGE): $(LIB_ALGORITHMS_OBJ_COVERAGE)
	echo "Making libalgorithms coverage"
	$(AR) ru $@ $(LIB_ALGORITHMS_OBJ_COVERAGE)
	$(RANLIB) $@

$(LIB_ALGORITHMS_RELEASE_SO): $(LIB_ALGORITHMS_OBJ_RELEASE)
	echo "Making libalgorithms shared release"
	$(CC) $(RELEASE_LDFLAGS) -shared $(LIB_ALGORITHMS_OBJ_RELEASE) -o $@ -lmt19937

$(LIB_ALGORITHMS_DEBUG_SO): $(LIB_ALGORITHMS_OBJ_DEBUG)
	echo "Making libalgorithms shared debug"
	$(CC) $(DEBUG_LDFLAGS) -shared $(LIB_ALGORITHMS_OBJ_DEBUG) -o $@ -lmt19937

$(LIB_ALGORITHMS_COVERAGE_SO): $(LIB_ALGORITHMS_OBJ_COVERAGE)
	echo "Making libalgorithms shared coverage"
	$(CC) $(COVERAGE_LDFLAGS) -shared $(LIB_ALGORITHMS_OBJ_COVERAGE) -o $@ -lmt19937
